version: '3.2'

services:
  kaldi-worker:
    build: ./worker/kaldi-worker
    networks:
      - backend
    restart: on-failure

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass kalditproject
    networks:
      - backend
    restart: always

  db:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: kalditproject
    volumes:
      - ./dfs/mariadb:/var/lib/mysql
    networks:
      - frontend
    restart: always

  proxy:
    image: "nginx:alpine"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - frontend
    restart: always

  api:
    build: ./server/api
    networks:
      - frontend
      - backend
    env_file:
      - './server/api/config/dev.env'
    volumes:
      - type: bind
        source: ./dfs/asr
        target: /www/data
    restart: on-failure

  web:
    build: ./server/web
    networks:
      - frontend
    restart: on-failure

networks:
  frontend:
  backend:
