version: '3.2'

services:
  kaldi-worker:
    build: ./worker/kaldi-worker
    networks:
      - backend
    restart: always
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass kalditproject
    networks:
      - backend
    restart: always

  db:
    image: "mariadb"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: kalditproject
      MYSQL_USER: api
      MYSQL_PASSWORD: api-server-password
      MYSQL_DATABASE: api
    networks:
      - frontend
    restart: always

  proxy:
    image: "nginx:alpine"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - frontend
    restart: always
    depends_on:
      - api
      - web

  api:
    build: ./server/api
    networks:
      - frontend
      - backend
    volumes:
      - type: bind
        source: ./dfs/asr
        target: /www/data
    restart: always
    depends_on:
      - db
      - redis

  web:
    build: ./server/web
    networks:
      - frontend
    restart: always
    depends_on:
      - api

networks:
  frontend:
  backend:
